const questions = [
    {
        "id": "mercury1",
        "question_no": "1",
        "question": "Lorem ipsum yada yada and that's all folks",
        "I": "Ooo eee",
        "II": "Ooo ah ah",
        "III": "Ting tang",
        "IV": "Walla walla",
        "next-route": "Bing bang",
    },
    {
        "id": "mercury2",
        "question_no": "2",
        "question": "Urrey",
        "I": "",
        "II": "surrey0@cafepress.com",
        "III": "surrey0@cafepress.com",
        "IV": "surrey0@cafepress.com",
        "next-route": "",
    },
    {
        "id": "mercury3",
        "question_no": "3",
        "question": "Urrey",
        "I": "",
        "II": "surrey0@cafepress.com",
        "III": "surrey0@cafepress.com",
        "IV": "surrey0@cafepress.com",
        "next-route": "",
    },
    {
        "id": "mercury4",
        "question_no": "4",
        "question": "Urrey",
        "I": "",
        "II": "surrey0@cafepress.com",
        "III": "surrey0@cafepress.com",
        "IV": "surrey0@cafepress.com",
        "next-route": "",
    },
    {
        "id": "mercury5",
        "question_no": "5",
        "question": "Urrey",
        "I": "",
        "II": "surrey0@cafepress.com",
        "III": "surrey0@cafepress.com",
        "IV": "surrey0@cafepress.com",
        "next-route": "",
    },
    {
        "id": "mercury6",
        "question_no": "6",
        "question": "Urrey",
        "I": "",
        "II": "surrey0@cafepress.com",
        "III": "surrey0@cafepress.com",
        "IV": "surrey0@cafepress.com",
        "next-route": "",
    },
    {
        "id": "mercury7",
        "question_no": "7",
        "question": "Urrey",
        "I": "",
        "II": "surrey0@cafepress.com",
        "III": "surrey0@cafepress.com",
        "IV": "surrey0@cafepress.com",
        "next-route": "",
    },
    {
        "id": "mercury8",
        "question_no": "8",
        "question": "Urrey",
        "I": "",
        "II": "surrey0@cafepress.com",
        "III": "surrey0@cafepress.com",
        "IV": "surrey0@cafepress.com",
        "next-route": "",
    },
    {
        "id": "mercury9",
        "question_no": "9",
        "question": "Urrey",
        "I": "",
        "II": "surrey0@cafepress.com",
        "III": "surrey0@cafepress.com",
        "IV": "surrey0@cafepress.com",
        "next-route": "",
    },
    {
        "id": "mercury10",
        "question_no": "10",
        "question": "Urrey",
        "I": "",
        "II": "surrey0@cafepress.com",
        "III": "surrey0@cafepress.com",
        "IV": "surrey0@cafepress.com",
        "next-route": "",
    },

]

export default { questions }